### ISSUE TITLE
Using this on a folder?

### ISSUE THREAD

**Issue by bronze** [matthewp/fs-cheerio#20]
Hi

i was wondering if this is usable on a `dist/` folder?
I was thinking of scanning my html files and editing it before publishing but im not sure how to go about scanning for `**/*.html` files

cheers

**Comment by matthewp** [comment]
You'd want to use a glob package like https://www.npmjs.com/package/fast-glob. fs-cheerio does not loading multiple files.

**Comment by bronze** [comment]
thank you very much!
